# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd8266657308e3dceb272f51a8adc8315d804a4e504ddfb0ff5d5ee261c43a9558fbe2b079e2d95fd44e514750567f16778f34aedac75fc0dc2fb611e36a12ce

test:
  secret_key_base: 516e8f97c2079c7730dcda7dfa80d610e29ff3b12b2d15a7331ec36ff25e42f70c9fc729062deecf91358d993d0bd2017cf00eff6f58594d52b2a9274a08ecdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
